
#line 3 "pac_scan.cc"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 88
#define YY_END_OF_BUFFER 89
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[404] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       89,   88,   24,   22,   87,   88,   23,   88,   87,   87,
       87,   87,   87,   73,   73,   87,   87,   87,   74,   74,
       74,   74,   74,   74,   74,   74,   74,   74,   74,   74,
       74,   74,   74,   87,   19,   20,   19,   19,   19,    2,
        3,   87,   21,   26,   28,   27,   28,   24,   78,    0,
       76,    0,   23,   75,    0,    0,    0,    0,    0,   11,
       83,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   85,   86,   73,    0,   81,   80,   77,   79,   82,
       74,   74,   74,   74,   74,   74,   74,   74,   74,   74,

       74,   74,   74,   74,   46,   74,   74,   74,   51,   74,
       74,   74,   84,    0,    0,    0,   13,   12,   18,    2,
        3,   26,    0,   26,   26,    0,    0,   75,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   61,
        0,    0,    0,    0,    0,    0,   72,   25,   74,   74,
       74,   74,   74,   74,   74,   74,   74,   74,   74,   34,
       74,   74,   74,   74,   74,   74,   74,   74,    0,    0,
        0,   18,   26,   26,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       63,    0,    0,    0,    0,    0,    0,    0,   74,   74,

       38,   74,   74,   74,   74,   30,   74,   32,   74,   74,
       74,   74,   74,   74,   36,   74,   74,    0,    0,    0,
       26,    0,    0,    0,   10,    0,    0,    0,    0,    0,
       56,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   37,   74,   74,   74,   74,   74,   74,
       74,   74,   74,   74,   74,   74,   74,   74,   74,   74,
       74,   74,   74,    0,   14,    0,    0,    6,    0,    0,
        0,    7,    0,    0,   58,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   71,   74,   74,   74,   74,   74,
       74,   74,   31,   74,   74,   74,   74,   49,   35,   50,

       74,   53,   74,   74,    0,    0,   15,    0,    0,    0,
        0,    0,    0,    0,    0,   62,    0,    0,    0,    0,
        0,    0,   74,   74,   74,   74,   74,   43,   74,   74,
       74,   74,   48,   74,   74,   74,    0,    0,    0,    4,
        5,    1,    9,    0,   59,    0,    0,   65,    0,    0,
        0,    0,    0,   29,   39,   40,   74,   42,   44,   45,
       33,   47,   52,   74,   74,    0,   16,    8,    0,    0,
        0,   66,   67,    0,    0,    0,   74,   74,   55,    0,
       57,    0,    0,    0,    0,   70,   41,   74,    0,    0,
        0,   68,   69,   54,   17,    0,   64,    0,    0,    0,

        0,   60,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    7,    8,    9,    1,   10,
       10,   10,   11,   10,   12,   13,   14,   15,   16,   16,
       16,   16,   16,   16,   16,   17,   17,   10,   10,   18,
       19,   20,   10,    1,   21,   21,   21,   21,   22,   21,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   24,   23,   23,   23,   23,   23,   23,   23,   23,
       10,   25,   10,   10,   26,    1,   27,   28,   29,   30,

       31,   32,   33,   34,   35,   23,   36,   37,   38,   39,
       40,   41,   42,   43,   44,   45,   46,   23,   47,   48,
       49,   50,   51,   52,   53,   10,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[54] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    3,    4,    5,    5,    5,    1,    1,    1,
        6,    6,    7,    7,    1,    7,    6,    6,    6,    6,
        6,    6,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[416] =
    {   0,
        0,    0,   51,   53,   67,  120,  169,    0,   76,   77,
      600,  601,  597,  601,  579,   57,    0,    0,   65,  214,
      601,  578,  576,   89,   92,   45,  576,   64,    0,  572,
       18,   70,  115,   50,   95,  562,  560,  564,  559,  554,
       95,  547,  552,  534,  601,  601,  107,  532,  570,  581,
        0,  573,  601,  556,  601,  601,   99,  578,  601,  128,
      601,  134,    0,    0,  117,  108,  548,  539,  546,  601,
      601,  539,  526,  540,  525,  540,  128,  532,  539,  526,
      529,  601,  601,  145,    0,  601,  601,  601,  601,  601,
        0,  553,  531,  538,  520,  524,  517,  529,  513,  513,

      513,  517,  517,  510,  522,  523,  135,  502,    0,  510,
      518,  504,  601,  508,  516,  497,  601,  601,    0,  543,
        0,  519,  154,  164,  246,  179,  274,    0,  512,  512,
      509,  495,  512,   82,  500,  493,  491,  157,  494,  601,
      146,  495,  502,  175,  505,  486,    0,  601,  497,  492,
      497,  488,  499,  498,  485,  485,  491,  474,  491,    0,
      475,  488,  477,  481,  484,  483,  476,  478,  472,  465,
      468,    0,  205,  292,  213,  310,  481,  476,  455,  474,
      474,  466,  457,  473,  460,  468,  469,  458,  456,  462,
      601,  463,  456,  463,  445,  445,  450,  453,  448,  437,

      160,  454,  451,  437,  450,    0,  438,  434,  434,  447,
      442,  433,  436,  434,  446,  432,  196,  427,  419,  438,
      443,  161,  428,  415,  601,  422,  433,  417,  411,  430,
      601,  420,  423,  422,  414,  411,  427,  419,  413,  417,
      411,  406,  412,    0,  398,  401,  397,  416,  401,  406,
      405,  402,  401,  404,  393,  398,  406,  404,  402,  388,
      385,  391,  391,  384,  601,  157,  382,  601,  388,  383,
      395,  601,  381,  380,  601,  391,  376,  386,  376,  379,
      371,  373,  383,  379,  601,  382,  373,  370,  365,  382,
      363,  367,    0,  366,  351,  349,  351,    0,    0,    0,

      327,    0,  326,  295,  309,  302,  601,  292,  279,  278,
      297,  267,  287,  286,  271,  601,  281,  280,  271,  269,
       63,  267,  254,  265,  262,  257,  250,    0,  240,  241,
      246,  252,    0,  240,  237,  235,  250,  221,  219,  601,
      601,  601,  601,  238,  601,  226,  238,  601,  219,  214,
      229,  218,  214,    0,    0,    0,  212,    0,    0,    0,
        0,    0,    0,  219,  203,  216,  601,  601,  203,  198,
      204,  601,  601,  194,  197,  191,  196,  186,    0,  201,
      601,  189,  196,  199,  177,  601,    0,  166,  139,  158,
      140,  601,  601,    0,  601,  134,  601,  113,   85,   43,

       39,  601,  601,  342,  349,  356,  363,  370,  372,  375,
      380,  387,  390,  393,  399
    } ;

static yyconst flex_int16_t yy_def[416] =
    {   0,
      403,    1,  404,  404,  405,  405,    1,    7,  406,  406,
      403,  403,  403,  403,  403,  407,  408,  409,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  403,  403,  403,  403,  403,  403,  403,
      411,  403,  403,  412,  403,  403,  412,  403,  403,  407,
      403,  407,  408,  413,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  414,  403,  403,  403,  403,  403,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,

      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  403,  403,  403,  403,  403,  403,  415,  403,
      411,  412,  412,  412,  412,  407,  407,  413,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  414,  403,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  403,  403,
      403,  415,  412,  125,  407,  127,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  410,  410,

      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  403,  403,  403,
      412,  407,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,

      410,  410,  410,  410,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  410,  410,  410,  403,
      403,  403,  403,  403,  403,  403,  410,  410,  403,  403,
      403,  403,  403,  410,  403,  403,  403,  403,  403,  403,

      403,  403,    0,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403
    } ;

static yyconst flex_int16_t yy_nxt[655] =
    {   0,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   23,   21,   21,   24,   25,   25,   26,   27,   28,
       29,   29,   29,   30,   12,   29,   31,   29,   32,   33,
       34,   35,   29,   29,   29,   29,   36,   29,   29,   37,
       38,   29,   39,   40,   41,   42,   43,   29,   29,   29,
       21,   44,   21,   46,   93,   46,   94,   47,   48,   47,
       48,   61,   86,   87,   49,  402,   49,   12,   50,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   55,   55,
       12,   62,   89,   90,   12,   12,   12,  401,  100,   56,
       56,   12,  351,   65,  352,   66,   95,  101,   67,   68,

       57,   57,   69,   84,   84,   84,   84,   84,   84,   96,
      182,  400,  122,  124,  124,   70,  183,   12,   12,   12,
       12,   50,   12,   12,   12,   12,   12,   12,   12,   12,
       12,  102,   61,   12,  109,  114,   85,   12,   12,   12,
      103,   97,  399,  110,   12,   98,  125,  131,  126,  126,
      115,  116,   62,  129,   99,  132,  130,  117,  141,   84,
       84,   84,  142,  163,  398,   61,  164,  122,  124,  124,
       12,   12,   12,   12,   12,   12,   21,   52,  173,  173,
       21,  127,  397,   61,  190,   62,  396,  187,  123,  395,
      191,  246,   29,  175,  175,   29,  306,   29,   29,   29,

       29,  125,  188,   62,  247,   29,  194,  307,   29,   29,
      394,   29,   29,   29,   29,   29,  195,   61,  196,  221,
      221,   53,   71,  393,  262,  392,  391,  222,  222,  123,
      263,  390,  389,  388,  387,  386,  385,   62,  384,  383,
       72,   73,   74,  382,   75,  381,  380,  379,   76,  378,
       77,  377,  376,   78,  375,  374,   79,  373,   80,   81,
      174,  174,  174,  372,  371,  370,  174,  174,  369,  368,
      123,  367,  174,  174,  174,  174,  174,  174,   61,  366,
      365,  364,  363,  362,  361,  360,  359,  358,  176,  176,
      176,  357,  356,  355,  176,  176,  354,  353,   62,  350,

      176,  176,  176,  176,  176,  176,  221,  221,  221,  349,
      348,  347,  221,  221,  346,  345,  344,  343,  221,  221,
      221,  221,  221,  221,  222,  222,  222,  342,  341,  340,
      222,  222,  339,  338,  337,  336,  222,  222,  222,  222,
      222,  222,   45,   45,   45,   45,   45,   45,   45,   51,
       51,   51,   51,   51,   51,   51,   54,   54,   54,   54,
       54,   54,   54,   60,  335,   60,   60,   60,   60,   60,
       63,  334,   63,   63,   63,   63,   63,   64,   64,   91,
       91,   91,  121,  333,  121,  121,  121,  122,  332,  122,
      331,  122,  122,  122,  128,  128,  128,  147,  147,  172,

      330,  172,  172,  172,  172,  172,  329,  328,  327,  326,
      325,  324,  323,  322,  321,  320,  319,  318,  317,  316,
      315,  314,  313,  312,  311,  310,  309,  308,  305,  304,
      303,  302,  301,  300,  299,  298,  297,  296,  295,  294,
      293,  292,  291,  290,  289,  288,  287,  286,  285,  284,
      283,  282,  281,  280,  279,  278,  277,  276,  275,  274,
      273,  272,  271,  270,  269,  268,  267,  123,  266,  265,
      264,  261,  260,  259,  258,  257,  256,  255,  254,  253,
      252,  251,  250,  249,  248,  245,  244,  243,  242,  241,
      240,  239,  238,  237,  236,  235,  234,  233,  232,  231,

      230,  229,  228,  227,  226,  225,  224,  223,  220,  219,
      218,  217,  216,  215,  214,  213,  212,  211,  210,  209,
      208,  207,  206,  205,  204,  203,  202,  201,  200,  199,
      198,  197,  193,  192,  189,  186,  185,  184,  181,  180,
      179,  178,  177,  123,  120,  171,  170,  169,  168,  167,
      166,  165,  162,  161,  160,  159,  158,  157,  156,  155,
      154,  153,  152,  151,  150,  149,  148,  146,  145,  144,
      143,  140,  139,  138,  137,  136,  135,  134,  133,   58,
      123,   71,  120,  119,  118,  113,  112,  111,  108,  107,
      106,  105,  104,   92,   88,   83,   82,   59,   58,  403,

       11,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403
    } ;

static yyconst flex_int16_t yy_chk[655] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,   31,    4,   31,    3,    3,    4,
        4,   16,   26,   26,    3,  401,    4,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    9,   10,
        5,   16,   28,   28,    5,    5,    5,  400,   34,    9,
       10,    5,  321,   19,  321,   19,   32,   34,   19,   19,

        9,   10,   19,   24,   24,   24,   25,   25,   25,   32,
      134,  399,   57,   57,   57,   19,  134,    5,    5,    5,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,   35,   60,    6,   41,   47,   24,    6,    6,    6,
       35,   33,  398,   41,    6,   33,   57,   66,   62,   62,
       47,   47,   60,   65,   33,   66,   65,   47,   77,   84,
       84,   84,   77,  107,  396,  222,  107,  123,  123,  123,
        6,    6,    6,    7,    7,    7,    7,    7,  124,  124,
        7,   62,  391,  126,  141,  222,  390,  138,  124,  389,
      141,  201,    7,  126,  126,    7,  266,    7,    7,    7,

        7,  123,  138,  126,  201,    7,  144,  266,    7,    7,
      388,    7,    7,    7,    7,    7,  144,  175,  144,  173,
      173,    7,   20,  385,  217,  384,  383,  175,  175,  173,
      217,  382,  380,  378,  377,  376,  375,  175,  374,  371,
       20,   20,   20,  370,   20,  369,  366,  365,   20,  364,
       20,  357,  353,   20,  352,  351,   20,  350,   20,   20,
      125,  125,  125,  349,  347,  346,  125,  125,  344,  339,
      125,  338,  125,  125,  125,  125,  125,  125,  127,  337,
      336,  335,  334,  332,  331,  330,  329,  327,  127,  127,
      127,  326,  325,  324,  127,  127,  323,  322,  127,  320,

      127,  127,  127,  127,  127,  127,  174,  174,  174,  319,
      318,  317,  174,  174,  315,  314,  313,  312,  174,  174,
      174,  174,  174,  174,  176,  176,  176,  311,  310,  309,
      176,  176,  308,  306,  305,  304,  176,  176,  176,  176,
      176,  176,  404,  404,  404,  404,  404,  404,  404,  405,
      405,  405,  405,  405,  405,  405,  406,  406,  406,  406,
      406,  406,  406,  407,  303,  407,  407,  407,  407,  407,
      408,  301,  408,  408,  408,  408,  408,  409,  409,  410,
      410,  410,  411,  297,  411,  411,  411,  412,  296,  412,
      295,  412,  412,  412,  413,  413,  413,  414,  414,  415,

      294,  415,  415,  415,  415,  415,  292,  291,  290,  289,
      288,  287,  286,  284,  283,  282,  281,  280,  279,  278,
      277,  276,  274,  273,  271,  270,  269,  267,  264,  263,
      262,  261,  260,  259,  258,  257,  256,  255,  254,  253,
      252,  251,  250,  249,  248,  247,  246,  245,  243,  242,
      241,  240,  239,  238,  237,  236,  235,  234,  233,  232,
      230,  229,  228,  227,  226,  224,  223,  221,  220,  219,
      218,  216,  215,  214,  213,  212,  211,  210,  209,  208,
      207,  205,  204,  203,  202,  200,  199,  198,  197,  196,
      195,  194,  193,  192,  190,  189,  188,  187,  186,  185,

      184,  183,  182,  181,  180,  179,  178,  177,  171,  170,
      169,  168,  167,  166,  165,  164,  163,  162,  161,  159,
      158,  157,  156,  155,  154,  153,  152,  151,  150,  149,
      146,  145,  143,  142,  139,  137,  136,  135,  133,  132,
      131,  130,  129,  122,  120,  116,  115,  114,  112,  111,
      110,  108,  106,  105,  104,  103,  102,  101,  100,   99,
       98,   97,   96,   95,   94,   93,   92,   81,   80,   79,
       78,   76,   75,   74,   73,   72,   69,   68,   67,   58,
       54,   52,   50,   49,   48,   44,   43,   42,   40,   39,
       38,   37,   36,   30,   27,   23,   22,   15,   13,   11,

      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "pac_scan.ll"
#line 2 "pac_scan.ll"
// $Id: pac_scan.ll 3361 2006-07-06 18:06:49Z rpang $

#include "pac_action.h"
#include "pac_array.h"
#include "pac_attr.h"
#include "pac_case.h"
#include "pac_common.h"
#include "pac_conn.h"
#include "pac_dataptr.h"
#include "pac_dataunit.h"
#include "pac_dbg.h"
#include "pac_decl.h"
#include "pac_exception.h"
#include "pac_expr.h"
#include "pac_flow.h"
#include "pac_id.h"
#include "pac_number.h"
#include "pac_output.h"
#include "pac_param.h"
#include "pac_parse.h"
#include "pac_record.h"
#include "pac_type.h"
#include "pac_utils.h"

int line_number = 1;

int begin_pac_primitive(int tok);
int end_pac_primitive();

int string_token(int tok)
	{
	yylval.str = copy_string(yytext);
	return tok;
	}

int char_token(int tok)
	{
	yylval.val = yytext[0];
	return tok;
	}

void include_file(const char *filename);

/* EC -- embedded code state */
/* PP -- PAC primitive state */
/* INCL -- @include line */

#line 787 "pac_scan.cc"

#define INITIAL 0
#define EC 1
#define INCL 2
#define PP 3
#define RE 4

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 62 "pac_scan.ll"


#line 979 "pac_scan.cc"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 404 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 601 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 64 "pac_scan.ll"
{
				BEGIN(INCL);
				}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 68 "pac_scan.ll"
/* skip whitespace */
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 70 "pac_scan.ll"
{
				BEGIN(INITIAL);
				include_file(yytext);
				}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 75 "pac_scan.ll"
{
				BEGIN(EC);
				return TOK_LPB_EXTERN;
				}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 79 "pac_scan.ll"
{
				BEGIN(EC);
				return TOK_LPB_HEADER;
				}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 83 "pac_scan.ll"
{
				BEGIN(EC);
				return TOK_LPB_CODE;
				}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 87 "pac_scan.ll"
{
				BEGIN(EC);
				return TOK_LPB_INIT;
				}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 91 "pac_scan.ll"
{
				BEGIN(EC);
				return TOK_LPB_CLEANUP;
				}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 95 "pac_scan.ll"
{
				BEGIN(EC);
				return TOK_LPB_MEMBER;
				}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 99 "pac_scan.ll"
{
				BEGIN(EC);
				return TOK_LPB_EOF;
				}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 103 "pac_scan.ll"
{
				BEGIN(EC);
				return TOK_LPB;
				}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 107 "pac_scan.ll"
{
				BEGIN(INITIAL);
				return TOK_RPB;
				}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 112 "pac_scan.ll"
return begin_pac_primitive(TOK_PAC_VAL);
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 113 "pac_scan.ll"
return begin_pac_primitive(TOK_PAC_SET); 
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 114 "pac_scan.ll"
return begin_pac_primitive(TOK_PAC_TYPE);
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 115 "pac_scan.ll"
return begin_pac_primitive(TOK_PAC_TYPEOF);
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 116 "pac_scan.ll"
return begin_pac_primitive(TOK_PAC_CONST_DEF);
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 118 "pac_scan.ll"
return string_token(TOK_EMBEDDED_STRING);
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 119 "pac_scan.ll"
return char_token(TOK_EMBEDDED_ATOM);
	YY_BREAK
case 20:
/* rule 20 can match eol */
YY_RULE_SETUP
#line 120 "pac_scan.ll"
{ ++line_number; return char_token(TOK_EMBEDDED_ATOM); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 122 "pac_scan.ll"
return end_pac_primitive();
	YY_BREAK
case 22:
/* rule 22 can match eol */
YY_RULE_SETUP
#line 124 "pac_scan.ll"
++line_number;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 125 "pac_scan.ll"
/* eat comments */
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 126 "pac_scan.ll"
/* eat whitespace */
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 128 "pac_scan.ll"
{
				BEGIN(RE);
				return TOK_BEGIN_RE;
				}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 133 "pac_scan.ll"
return string_token(TOK_REGEX);
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 135 "pac_scan.ll"
{
				BEGIN(INITIAL);
				return TOK_END_RE;
				}
	YY_BREAK
case 28:
/* rule 28 can match eol */
YY_RULE_SETUP
#line 140 "pac_scan.ll"
return yytext[0];
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 142 "pac_scan.ll"
return TOK_ANALYZER;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 143 "pac_scan.ll"
return TOK_ENUM;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 144 "pac_scan.ll"
return TOK_EXTERN;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 145 "pac_scan.ll"
return TOK_FLOW;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 146 "pac_scan.ll"
return TOK_FUNCTION;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 147 "pac_scan.ll"
return TOK_LET;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 148 "pac_scan.ll"
return TOK_REFINE;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 149 "pac_scan.ll"
return TOK_TYPE;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 151 "pac_scan.ll"
return TOK_ALIGN;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 152 "pac_scan.ll"
return TOK_CASE;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 153 "pac_scan.ll"
return TOK_CASEFUNC;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 154 "pac_scan.ll"
return TOK_CASETYPE;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 155 "pac_scan.ll"
return TOK_CONNECTION;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 156 "pac_scan.ll"
{
				yylval.val = AnalyzerDataUnit::DATAGRAM;
				return TOK_DATAUNIT;
				}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 160 "pac_scan.ll"
return TOK_DEFAULT;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 161 "pac_scan.ll"
{
				yylval.val = AnalyzerFlow::DOWN;
				return TOK_FLOWDIR;
				}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 165 "pac_scan.ll"
{
				yylval.val = AnalyzerDataUnit::FLOWUNIT;
				return TOK_DATAUNIT;
				}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 169 "pac_scan.ll"
return TOK_OF;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 170 "pac_scan.ll"
return TOK_OFFSETOF;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 171 "pac_scan.ll"
return TOK_PADDING;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 172 "pac_scan.ll"
return TOK_RECORD;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 173 "pac_scan.ll"
return TOK_SIZEOF;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 174 "pac_scan.ll"
return TOK_TO;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 175 "pac_scan.ll"
return TOK_TYPEATTR;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 176 "pac_scan.ll"
{
				yylval.val = AnalyzerFlow::UP;
				return TOK_FLOWDIR;
				}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 180 "pac_scan.ll"
return TOK_WITHCONTEXT;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 181 "pac_scan.ll"
return TOK_WITHINPUT;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 183 "pac_scan.ll"
return TOK_ATTR_ALSO;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 184 "pac_scan.ll"
return TOK_ATTR_BYTEORDER;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 185 "pac_scan.ll"
return TOK_ATTR_CHECK;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 186 "pac_scan.ll"
return TOK_ATTR_CHUNKED;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 187 "pac_scan.ll"
return TOK_ATTR_EXPORTSOURCEDATA;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 188 "pac_scan.ll"
return TOK_ATTR_IF;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 189 "pac_scan.ll"
return TOK_ATTR_LENGTH;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 190 "pac_scan.ll"
return TOK_ATTR_LET;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 191 "pac_scan.ll"
return TOK_ATTR_LINEBREAKER;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 192 "pac_scan.ll"
return TOK_ATTR_ONELINE;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 193 "pac_scan.ll"
return TOK_ATTR_REFCOUNT;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 194 "pac_scan.ll"
return TOK_ATTR_REQUIRES;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 195 "pac_scan.ll"
return TOK_ATTR_RESTOFDATA;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 196 "pac_scan.ll"
return TOK_ATTR_RESTOFFLOW;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 197 "pac_scan.ll"
return TOK_ATTR_TRANSIENT;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 198 "pac_scan.ll"
return TOK_ATTR_UNTIL;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 200 "pac_scan.ll"
{
				int n;
				sscanf(yytext + 2, "%x", &n);
				yylval.num = new Number(yytext, n);
				return TOK_NUMBER;
				}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 207 "pac_scan.ll"
{
				int n;
				sscanf(yytext, "%d", &n);
				yylval.num = new Number(yytext, n);
				return TOK_NUMBER;
				}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 214 "pac_scan.ll"
{
				yylval.id = new ID(yytext);
				return TOK_ID;
				}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 219 "pac_scan.ll"
{
				yylval.id = new ID(yytext);
				return TOK_ID;
				}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 224 "pac_scan.ll"
return string_token(TOK_STRING);
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 226 "pac_scan.ll"
return TOK_EQUAL;
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 227 "pac_scan.ll"
return TOK_NEQ;
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 228 "pac_scan.ll"
return TOK_GE;
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 229 "pac_scan.ll"
return TOK_LE;
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 230 "pac_scan.ll"
return TOK_LSHIFT;
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 231 "pac_scan.ll"
return TOK_RSHIFT;
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 232 "pac_scan.ll"
return TOK_AND;
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 233 "pac_scan.ll"
return TOK_OR;
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 234 "pac_scan.ll"
return TOK_PLUSEQ;
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 235 "pac_scan.ll"
return TOK_RIGHTARROW;
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 237 "pac_scan.ll"
return yytext[0];
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 239 "pac_scan.ll"
ECHO;
	YY_BREAK
#line 1571 "pac_scan.cc"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(EC):
case YY_STATE_EOF(INCL):
case YY_STATE_EOF(PP):
case YY_STATE_EOF(RE):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 404 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 404 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 403);

	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 239 "pac_scan.ll"



void begin_RE()
	{
	BEGIN(RE);
	}

void end_RE()
	{
	BEGIN(INITIAL);
	}

// The DECL state is deprecated
void begin_decl()
	{
	// BEGIN(DECL);
	}

void end_decl()
	{
	// BEGIN(INITIAL);
	}

int begin_pac_primitive(int tok)
	{
	BEGIN(PP);
	return tok;
	}

int end_pac_primitive()
	{
	BEGIN(EC);
	return TOK_END_PAC;
	}

const int MAX_INCLUDE_DEPTH = 100;

struct IncludeState {
	YY_BUFFER_STATE yystate;
	string input_filename;
	int line_number;
};

IncludeState include_stack[MAX_INCLUDE_DEPTH];
int include_stack_ptr = 0;

void switch_to_file(FILE *fp)
	{
	yy_switch_to_buffer(yy_create_buffer(fp,YY_BUF_SIZE));
	}

void switch_to_file(const char *filename)
	{
	if ( include_stack_ptr >= MAX_INCLUDE_DEPTH )
		{
		fprintf( stderr, "Includes nested too deeply" );
		exit( 1 );
		}

	IncludeState state = 
		{ YY_CURRENT_BUFFER, input_filename, line_number };
	include_stack[include_stack_ptr++] = state;

	FILE *fp = fopen(filename, "r");

	if ( ! fp )
		{
		fprintf(stderr, "%s:%d: error: cannot include file \"%s\"\n", 
			input_filename.c_str(), line_number,filename);
		--include_stack_ptr;
		return;
		}

	yyin = fp;
	input_filename = string(filename);
	line_number = 1;
	switch_to_file(yyin);
	fprintf(stderr, "switching to file %s\n", input_filename.c_str());
	}

void include_file(const char *filename)
	{
	ASSERT(filename);

	string full_filename;
	if ( filename[0] == '/' || filename[0] == '.' )
		full_filename = filename;
	else
		{
		int i;
		for ( i = 0; i < (int) FLAGS_include_directories.size(); ++i )
			{
			full_filename = FLAGS_include_directories[i] + filename;
			DEBUG_MSG("Try include file: \"%s\"\n", 
				full_filename.c_str());
			if ( access(full_filename.c_str(), R_OK) == 0 )
				break;
			}
		if ( i >= (int) FLAGS_include_directories.size() )
			full_filename = filename;
		}

	switch_to_file(full_filename.c_str());
	}

int yywrap()
	{
	yy_delete_buffer(YY_CURRENT_BUFFER);
	--include_stack_ptr;
	if ( include_stack_ptr < 0 )
		return 1;

	IncludeState state = include_stack[include_stack_ptr];
	yy_switch_to_buffer(state.yystate);
	input_filename = state.input_filename;
	line_number = state.line_number;
	return 0;
	}

