#!/bin/sh

buildinfo="bro-earth-orbit, Mon Oct  3 17:45:15 EDT 2011, Debugging support: no"
prefix=/usr/local/bro
exec_prefix=${prefix}
exec_prefix_set=no

usage="\
Usage: broccoli-config [--build] [--prefix[=DIR]] [--exec-prefix[=DIR]] [--version] [--libs] [--cflags] [--config]"

if test $# -eq 0; then
      echo "${usage}" 1>&2
      exit 1
fi

while test $# -gt 0; do
  case "$1" in
  -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
  *) optarg= ;;
  esac

  case $1 in
    --build)
      echo $buildinfo
      ;;
    --prefix=*)
      prefix=$optarg
      if test $exec_prefix_set = no ; then
        exec_prefix=$optarg
      fi
      ;;
    --prefix)
      echo $prefix
      ;;
    --exec-prefix=*)
      exec_prefix=$optarg
      exec_prefix_set=yes
      ;;
    --exec-prefix)
      echo $exec_prefix
      ;;
    --version)
      echo 1.5.0
      ;;
    --cflags)
      if test ${prefix}/include != /usr/include ; then
        includes=-I${prefix}/include
      fi
      echo $includes -I$prefix/include  -DBROCCOLI 
      ;;
    --libs)
      libdirs=-L${exec_prefix}/lib
      echo $libdirs -lbroccoli 
      ;;
    --config)
      echo /usr/local/bro/etc/broccoli.conf
      ;;
    *)
      echo "${usage}" 1>&2
      exit 1
      ;;
  esac
  shift
done

exit 0
