
#line 3 "hf.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 16
#define YY_END_OF_BUFFER 17
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[330] =
    {   0,
        0,    0,   17,   13,   15,   12,   13,   13,   13,   14,
       10,   12,    0,    0,   13,   13,   13,   11,   12,    0,
        0,    0,    0,   13,   13,   13,   10,   11,   12,    0,
        0,    0,    4,    0,    0,    4,   13,   13,   13,   11,
       11,   12,    0,    0,    0,    4,    0,    0,    0,   13,
        4,   13,   13,   13,   10,   11,    0,    0,    0,    5,
        4,    4,    0,    0,    4,    4,    5,   13,   13,   13,
        2,   11,    0,    0,    0,    5,    0,    4,    4,    0,
        0,    0,   13,    4,    4,   13,    5,   13,   13,   13,
        2,    0,    0,    0,    6,    5,    5,    4,    4,    0,

        0,    4,    4,    5,    5,    6,   13,   13,   13,    2,
        0,    0,    0,    6,    0,    5,    5,    0,    4,    4,
        0,    1,    0,   13,    4,    4,   13,    5,    5,   13,
        6,   13,   13,   13,    0,    0,    0,    7,    6,    6,
        5,    5,    4,    4,    1,    4,    4,    5,    5,    6,
        6,    7,   13,   13,   13,    0,    0,    0,    7,    0,
        6,    6,    0,    5,    5,    0,    4,    4,    0,    1,
       13,    4,    4,   13,    5,    5,   13,    6,    6,   13,
        7,   13,   13,   13,    0,    0,    0,    8,    7,    7,
        6,    6,    5,    5,    4,    4,    4,    4,    5,    5,

        6,    6,    7,    7,    8,   13,   13,   13,    0,    0,
        0,    8,    0,    7,    7,    0,    6,    6,    0,    5,
        5,    0,    4,    4,    0,   13,    4,    4,   13,    5,
        5,   13,    6,    6,   13,    7,    7,   13,    8,   13,
       13,   13,    0,    0,    0,    9,    8,    8,    7,    7,
        6,    6,    5,    5,    4,    4,    4,    4,    5,    5,
        6,    6,    7,    7,    8,    8,    9,   13,   13,   13,
        0,    3,    9,    8,    8,    7,    7,    6,    6,    5,
        5,    4,    4,    4,    4,    5,    5,    6,    6,    7,
        7,    8,    8,    9,    3,   13,    0,    3,    9,    8,

        7,    6,    5,    4,    4,    5,    6,    7,    8,    9,
        3,   13,    3,    9,    8,    7,    6,    5,    4,    4,
        5,    6,    7,    8,    9,    3,    3,    3,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    1,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    5,    1,    1,
        1,    1,    1,    1,    6,    6,    6,    6,    6,    6,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    6,    6,    6,    6,

        6,    6,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[7] =
    {   0,
        1,    1,    2,    3,    4,    5
    } ;

static yyconst flex_int16_t yy_base[483] =
    {   0,
        0,    0,  729,  726,  730,    4,    9,   11,  722,  730,
        0,   14,  721,  720,  719,   17,   20,   24,   25,  715,
      712,    0,   29,   30,   33,   36,    0,  710,   39,    0,
      706,  703,  700,    0,  698,   41,   44,   47,  694,   51,
        0,    0,  691,  688,    0,  685,    0,   53,    0,   54,
       57,   60,   63,   66,    0,  683,    0,  679,  676,  670,
      664,  658,    0,  653,   69,   72,   75,   78,   81,  646,
        0,    0,  640,  637,    0,  631,    0,    0,  625,    0,
       85,    0,   86,   89,  619,   92,   95,   98,  101,  104,
        0,    0,  613,  607,  601,  559,  553,  547,  541,    0,

      536,  107,  110,  113,  116,  119,  122,  125,  499,  730,
      493,  487,    0,  481,    0,    0,  451,    0,    0,  445,
        0,    0,    0,  128,  131,  439,  134,  137,  415,  140,
      143,  146,  149,  152,    0,  409,  391,  375,  371,  368,
      365,  362,  359,  356,    0,  155,  158,  161,  164,  167,
      170,  173,  176,  179,  353,  350,  347,    0,  344,    0,
        0,  341,    0,    0,  338,    0,    0,  335,    0,  730,
      182,  185,  332,  188,  191,  329,  194,  197,  326,  200,
      203,  206,  209,  212,    0,  323,  320,  317,  314,  311,
      308,  305,  302,  299,  296,  293,  215,  218,  221,  224,

      227,  230,  233,  236,  239,  242,  245,  290,  287,  284,
        0,  278,    0,    0,  275,    0,    0,  272,    0,    0,
      269,    0,    0,  266,    0,  248,  251,  263,  254,  257,
      260,  260,  263,  257,  266,  269,  254,  272,  275,  278,
      281,  284,    0,  251,    0,    0,  248,    0,  245,    0,
      236,    0,  230,    0,  224,    0,  287,  290,  293,  296,
      299,  302,  305,  308,  311,  314,  317,  320,  323,  218,
      212,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  326,  206,  329,  203,  332,  200,  335,
      197,  338,  194,  341,  344,  347,    0,    0,    0,    0,

        0,    0,    0,    0,  350,  353,  356,  359,  362,  365,
      368,  191,    0,  730,  730,  730,  730,  730,  730,    0,
        0,    0,    0,    0,    0,  371,  730,    0,  730,  377,
      190,  380,  383,  386,  389,  392,  187,  183,  395,  398,
      401,  181,  173,  166,  404,  407,  410,  413,  416,  161,
      154,  147,  419,  422,  425,  428,  431,  145,  142,  140,
      434,  437,  440,  443,  446,  135,  449,  452,  134,  130,
      126,  455,  458,  461,  464,  467,  470,  473,  118,  476,
      479,  482,  485,  488,  111,  491,  494,  105,  497,  500,
      100,   98,   93,  503,  506,  509,  512,  515,  518,  521,

      524,  527,   91,  530,  533,  536,  539,  542,   87,  545,
      548,   82,  551,  554,   73,  557,  560,   67,  563,  566,
      569,  572,  575,  578,  581,  584,  587,  590,  593,  596,
      599,  602,  605,  608,   61,  611,  614,   58,  617,  620,
       55,  623,  626,   48,  629,  632,   37,  635,  638,  641,
      644,  647,  650,  653,  656,  659,  662,  665,  668,  671,
      674,  677,  680,   31,  683,   26,  686,   21,  689,   15,
      692,    9,  695,    8,  698,  701,  704,  707,  710,  713,
      716,  719
    } ;

static yyconst flex_int16_t yy_def[483] =
    {   0,
      329,    1,  329,  330,  329,  329,  330,    7,    7,  329,
      331,    6,  332,  333,    9,    9,    8,  329,    6,  334,
      335,  336,  329,    9,    9,    8,  337,   18,  329,  338,
      339,  340,  341,  342,   23,    8,    8,   25,    9,  329,
      343,  344,  345,  346,  347,  348,  349,  329,  350,    9,
       36,    9,    9,   25,  351,   40,  352,  353,  354,  355,
      356,  357,  358,   48,   25,   36,   36,   36,   53,    9,
      359,  360,  361,  362,  363,  364,  365,  366,  367,  368,
      329,  369,    9,   65,    9,    9,   67,    9,    9,   53,
      370,  371,  372,  373,  374,  375,  376,  377,  378,  379,

       81,   53,   65,   65,   67,   67,   67,   89,    9,  329,
      380,  381,  382,  383,  384,  385,  386,  387,  388,  389,
      390,  391,  392,    9,  102,    9,    9,  104,    9,    9,
      106,    9,    9,   89,  393,  394,  395,  396,  397,  398,
      399,  400,  401,  402,  403,   89,  102,  102,  104,  104,
      106,  106,  106,  133,    9,  404,  405,  406,  407,  408,
      409,  410,  411,  412,  413,  414,  415,  416,  417,  329,
        9,  146,    9,    9,  148,    9,    9,  150,    9,    9,
      152,    9,    9,  133,  418,  419,  420,  421,  422,  423,
      424,  425,  426,  427,  428,  429,  133,  146,  146,  148,

      148,  150,  150,  152,  152,  152,  183,    9,  430,  431,
      432,  433,  434,  435,  436,  437,  438,  439,  440,  441,
      442,  443,  444,  445,  446,    9,  197,    9,    9,  199,
        9,    9,  201,    9,    9,  203,    9,    9,  205,    9,
        9,  183,  447,  448,  449,  450,  451,  452,  453,  454,
      455,  456,  457,  458,  459,  460,    9,  197,    9,  199,
        9,  201,    9,  203,    9,  205,    9,    9,  241,    9,
      461,  462,  463,  464,  465,  466,  467,  468,  469,  470,
      471,  472,  473,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,  241,  474,  475,  476,  477,

      478,  479,  480,  481,    9,    9,    9,    9,    9,    9,
        9,    9,  482,  329,  329,  329,  329,  329,  329,    9,
        9,    9,    9,    9,    9,    9,  329,    9,    0,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,

      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329
    } ;

static yyconst flex_int16_t yy_nxt[737] =
    {   0,
        4,    5,    4,    6,    7,    8,   11,   12,   13,   14,
       10,  245,  225,   15,   14,   16,   17,   19,  222,   20,
       21,   24,   25,   20,  219,   26,   27,   28,   29,  216,
       30,   34,   35,   33,  213,   36,   31,   37,   38,   30,
      187,   39,   42,   13,   46,   50,   51,   44,   52,   53,
       43,  169,   54,   55,   56,   63,   64,   62,  166,   65,
       61,  163,   66,   60,  160,   67,   58,   68,   69,   57,
      137,   70,   79,   83,   84,   78,  121,   85,   76,   86,
       87,   74,   88,   89,   73,  118,   90,  100,  101,   99,
      115,  102,   98,  170,  103,   97,   94,  104,   96,  100,

      105,   95,  145,  106,   93,  107,  108,   92,   80,  109,
      120,  124,  125,  119,   77,  126,  117,  127,  128,  116,
      122,  129,  114,  130,  131,  112,  132,  133,  111,   59,
      134,  144,  110,  146,  143,   63,  147,  142,   47,  148,
      141,   55,  149,  140,   91,  150,  139,   81,  151,  138,
       32,  152,  136,  153,  154,  135,   71,  155,  168,  171,
      172,  167,   34,  173,  165,  174,  175,  164,   42,  176,
      162,  177,  178,  161,   27,  179,  159,  180,  181,  157,
      182,  183,  156,   48,  184,  196,   13,  197,  195,   40,
      198,  194,   18,  199,  193,  268,  200,  192,  238,  201,

      191,  235,  202,  190,  232,  203,  189,  229,  204,  188,
      226,  205,  186,  206,  207,  185,  245,  208,  224,  226,
      227,  223,  206,  228,  221,  229,  230,  220,  225,  231,
      218,  232,  233,  217,  222,  234,  215,  235,  236,  214,
      219,  237,  212,  238,  239,  210,  240,  241,  209,  216,
      242,  256,  213,  257,  255,  245,  258,  254,  180,  259,
      253,  177,  260,  252,  174,  261,  251,  171,  262,  250,
      225,  263,  249,  222,  264,  248,  219,  265,  247,  216,
      266,  246,  213,  267,  244,  268,  269,  243,  245,  270,
      283,  187,  284,  282,  153,  285,  281,  225,  286,  280,

      169,  287,  279,  222,  288,  278,  166,  289,  277,  219,
      290,  276,  163,  291,  275,  216,  292,  274,  160,  293,
      273,  213,  294,  272,  211,  295,  271,  187,  296,  304,
      130,  305,  303,  127,  306,  302,  124,  307,  301,  169,
      308,  300,  166,  309,  299,  163,  310,  298,  160,  311,
      297,  187,  312,  319,  137,  320,  318,  107,  321,  317,
      169,  322,  316,  121,  323,  315,  166,  324,  314,  118,
      325,  313,  163,  326,  327,  115,  328,    9,    9,  160,
        9,    9,   21,   21,   21,   20,   20,   20,   30,   30,
       30,   31,   31,   31,   33,  158,   33,   43,   43,   43,

       44,   44,   44,   46,   46,   46,   57,   57,   57,   58,
       58,   58,   60,  137,   60,   61,   61,   61,   62,   86,
       62,   73,   73,   73,   74,   74,   74,   76,   76,   76,
       78,   78,   78,   79,   79,   79,   92,   92,   92,   93,
       93,   93,   95,   83,   95,   96,   96,   96,   97,  121,
       97,   98,   98,   98,   99,  118,   99,  111,  111,  111,
      112,  112,  112,  114,  114,  114,  116,  116,  116,  117,
      117,  117,  119,  119,  119,  120,  120,  120,  135,  135,
      135,  136,  136,  136,  138,  115,  138,  139,  139,  139,
      140,  137,  140,  141,  141,  141,  142,   94,  142,  143,

      143,  143,  144,   68,  144,  156,  156,  156,  157,  157,
      157,  159,  159,  159,  161,  161,  161,  162,  162,  162,
      164,  164,  164,  165,  165,  165,  167,  167,  167,  168,
      168,  168,  185,  185,  185,  186,  186,  186,  188,  123,
      188,  189,  189,  189,  190,  121,  190,  191,  191,  191,
      192,   80,  192,  193,  193,  193,  194,  118,  194,  195,
      195,  195,  196,   77,  196,  209,  209,  209,  210,  210,
      210,  212,  212,  212,  214,  214,  214,  215,  215,  215,
      217,  217,  217,  218,  218,  218,  220,  220,  220,  221,
      221,  221,  223,  223,  223,  224,  224,  224,  243,  243,

      243,  244,  244,  244,  246,  115,  246,  247,  247,  247,
      248,  113,  248,  249,  249,  249,  250,   94,  250,  251,
      251,  251,  252,   50,  252,  253,  253,  253,  254,   80,
      254,  255,  255,  255,  256,   77,  256,  271,  271,  271,
      272,   94,  272,  273,   59,  273,  274,  274,  274,  275,
       37,  275,  276,  276,  276,  277,   82,  277,  278,  278,
      278,  279,   80,  279,  280,  280,  280,  281,   47,  281,
      282,  282,  282,  283,   77,  283,  297,  297,  297,  298,
       75,  298,  299,   59,  299,  300,   72,  300,  301,   47,
      301,  302,   59,  302,  303,   32,  303,  304,   16,  304,

      313,   49,  313,  314,   47,  314,  315,   45,  315,  316,
       32,  316,  317,   41,  317,  318,   32,  318,  319,   13,
      319,  327,   23,  327,   13,   22,    9,   10,  329,    3,
      329,  329,  329,  329,  329,  329
    } ;

static yyconst flex_int16_t yy_chk[737] =
    {   0,
        1,    1,    1,    1,    1,    1,    6,    6,    6,    6,
        7,  474,  472,    7,    8,    8,    8,   12,  470,   12,
       16,   16,   16,   17,  468,   17,   18,   18,   19,  466,
       19,   23,   23,   24,  464,   24,   25,   25,   25,   26,
      447,   26,   29,   29,   36,   36,   36,   37,   37,   37,
       38,  444,   38,   40,   40,   48,   48,   50,  441,   50,
       51,  438,   51,   52,  435,   52,   53,   53,   53,   54,
      418,   54,   65,   65,   65,   66,  415,   66,   67,   67,
       67,   68,   68,   68,   69,  412,   69,   81,   81,   83,
      409,   83,   84,  403,   84,   86,  393,   86,   87,  392,

       87,   88,  391,   88,   89,   89,   89,   90,  388,   90,
      102,  102,  102,  103,  385,  103,  104,  104,  104,  105,
      379,  105,  106,  106,  106,  107,  107,  107,  108,  371,
      108,  124,  370,  124,  125,  369,  125,  127,  366,  127,
      128,  360,  128,  130,  359,  130,  131,  358,  131,  132,
      352,  132,  133,  133,  133,  134,  351,  134,  146,  146,
      146,  147,  350,  147,  148,  148,  148,  149,  344,  149,
      150,  150,  150,  151,  343,  151,  152,  152,  152,  153,
      153,  153,  154,  342,  154,  171,  338,  171,  172,  337,
      172,  174,  331,  174,  175,  312,  175,  177,  293,  177,

      178,  291,  178,  180,  289,  180,  181,  287,  181,  182,
      285,  182,  183,  183,  183,  184,  271,  184,  197,  197,
      197,  198,  270,  198,  199,  199,  199,  200,  255,  200,
      201,  201,  201,  202,  253,  202,  203,  203,  203,  204,
      251,  204,  205,  205,  205,  206,  206,  206,  207,  249,
      207,  226,  247,  226,  227,  244,  227,  229,  237,  229,
      230,  234,  230,  232,  231,  232,  233,  228,  233,  235,
      224,  235,  236,  221,  236,  238,  218,  238,  239,  215,
      239,  240,  212,  240,  241,  241,  241,  242,  210,  242,
      257,  209,  257,  258,  208,  258,  259,  196,  259,  260,

      195,  260,  261,  194,  261,  262,  193,  262,  263,  192,
      263,  264,  191,  264,  265,  190,  265,  266,  189,  266,
      267,  188,  267,  268,  187,  268,  269,  186,  269,  284,
      179,  284,  286,  176,  286,  288,  173,  288,  290,  168,
      290,  292,  165,  292,  294,  162,  294,  295,  159,  295,
      296,  157,  296,  305,  156,  305,  306,  155,  306,  307,
      144,  307,  308,  143,  308,  309,  142,  309,  310,  141,
      310,  311,  140,  311,  326,  139,  326,  330,  330,  138,
      330,  330,  332,  332,  332,  333,  333,  333,  334,  334,
      334,  335,  335,  335,  336,  137,  336,  339,  339,  339,

      340,  340,  340,  341,  341,  341,  345,  345,  345,  346,
      346,  346,  347,  136,  347,  348,  348,  348,  349,  129,
      349,  353,  353,  353,  354,  354,  354,  355,  355,  355,
      356,  356,  356,  357,  357,  357,  361,  361,  361,  362,
      362,  362,  363,  126,  363,  364,  364,  364,  365,  120,
      365,  367,  367,  367,  368,  117,  368,  372,  372,  372,
      373,  373,  373,  374,  374,  374,  375,  375,  375,  376,
      376,  376,  377,  377,  377,  378,  378,  378,  380,  380,
      380,  381,  381,  381,  382,  114,  382,  383,  383,  383,
      384,  112,  384,  386,  386,  386,  387,  111,  387,  389,

      389,  389,  390,  109,  390,  394,  394,  394,  395,  395,
      395,  396,  396,  396,  397,  397,  397,  398,  398,  398,
      399,  399,  399,  400,  400,  400,  401,  401,  401,  402,
      402,  402,  404,  404,  404,  405,  405,  405,  406,  101,
      406,  407,  407,  407,  408,   99,  408,  410,  410,  410,
      411,   98,  411,  413,  413,  413,  414,   97,  414,  416,
      416,  416,  417,   96,  417,  419,  419,  419,  420,  420,
      420,  421,  421,  421,  422,  422,  422,  423,  423,  423,
      424,  424,  424,  425,  425,  425,  426,  426,  426,  427,
      427,  427,  428,  428,  428,  429,  429,  429,  430,  430,

      430,  431,  431,  431,  432,   95,  432,  433,  433,  433,
      434,   94,  434,  436,  436,  436,  437,   93,  437,  439,
      439,  439,  440,   85,  440,  442,  442,  442,  443,   79,
      443,  445,  445,  445,  446,   76,  446,  448,  448,  448,
      449,   74,  449,  450,   73,  450,  451,  451,  451,  452,
       70,  452,  453,  453,  453,  454,   64,  454,  455,  455,
      455,  456,   62,  456,  457,  457,  457,  458,   61,  458,
      459,  459,  459,  460,   60,  460,  461,  461,  461,  462,
       59,  462,  463,   58,  463,  465,   56,  465,  467,   46,
      467,  469,   44,  469,  471,   43,  471,  473,   39,  473,

      475,   35,  475,  476,   33,  476,  477,   32,  477,  478,
       31,  478,  479,   28,  479,  480,   21,  480,  481,   20,
      481,  482,   15,  482,   14,   13,    9,    4,    3,  329,
      329,  329,  329,  329,  329,  329
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "hf.l"
#include "config.h"
#include <sys/types.h>
#include <sys/socket.h>
#include <sys/time.h>
#include <sys/stat.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#ifdef NEED_NAMESER_COMPAT_H
#include <arpa/nameser_compat.h>
#else
#include <arpa/nameser.h>
#endif
#ifndef NS_MAXDNAME
#define NS_MAXDNAME 1025
#endif
#ifndef NS_INADDRSZ
#define NS_INADDRSZ 4
#endif
#ifndef NS_IN6ADDRSZ
#define NS_IN6ADDRSZ 16
#endif
#include <ctype.h>
#include <errno.h>
#ifdef HAVE_MEMORY_H
#include <memory.h>
#endif
#include <netdb.h>
#include <resolv.h>
#include <setjmp.h>
#include <signal.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include "gnuc.h"
#ifdef HAVE_OS_PROTO_H
#include "os-proto.h"
#endif
#include "setsignal.h"
#include "nb_dns.h"
#undef yywrap
#ifdef FLEX_SCANNER
#define YY_NO_UNPUT
#endif
int yywrap(void);
int yylex(void);
void convert(const char *, int);
#ifdef HAVE_ASYNC_DNS
#define ECHO \
if (!lookup_pass) { (void) fwrite( yytext, yyleng, 1, yyout ); }
int lookup_pass;		/* true if lookup only */
#endif
int linemode;		/* convert at most one entry per line */
int triedone;
#line 810 "hf.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 70 "hf.l"



#line 1001 "hf.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 330 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 730 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 73 "hf.l"
convert(yytext, 1);
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 74 "hf.l"
convert(yytext, 0);
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 76 "hf.l"
convert(yytext, 1);
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 77 "hf.l"
convert(yytext, 1);
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 78 "hf.l"
convert(yytext, 1);
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 79 "hf.l"
convert(yytext, 1);
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 80 "hf.l"
convert(yytext, 1);
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 81 "hf.l"
convert(yytext, 1);
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 82 "hf.l"
convert(yytext, 1);
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 84 "hf.l"
ECHO;		/* anti-backtrack */
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 85 "hf.l"
ECHO;		/* anti-backtrack */
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 87 "hf.l"
ECHO;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 88 "hf.l"
ECHO;
	YY_BREAK
case 14:
/* rule 14 can match eol */
YY_RULE_SETUP
#line 89 "hf.l"
{
			ECHO;
			triedone = 0;
			}
	YY_BREAK
case 15:
/* rule 15 can match eol */
YY_RULE_SETUP
#line 94 "hf.l"
{
			ECHO;
			triedone = 0;
			}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 99 "hf.l"
ECHO;
	YY_BREAK
#line 1172 "hf.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 330 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 330 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 329);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 99 "hf.l"



/*
 * Copyright (c) 1989, 1990, 1991, 1992, 1993, 1994, 1996, 1998, 1999, 2000, 2001, 2002, 2004
 *	The Regents of the University of California.  All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that: (1) source code distributions
 * retain the above copyright notice and this paragraph in its entirety, (2)
 * distributions including binary code include the above copyright notice and
 * this paragraph in its entirety in the documentation or other materials
 * provided with the distribution, and (3) all advertising materials mentioning
 * features or use of this software display the following acknowledgement:
 * ``This product includes software developed by the University of California,
 * Lawrence Berkeley Laboratory and its contributors.'' Neither the name of
 * the University nor the names of its contributors may be used to endorse
 * or promote products derived from this software without specific prior
 * written permission.
 * THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

#ifndef lint
static const char copyright[] =
    "@(#) Copyright (c) 1989, 1990, 1991, 1992, 1993, 1994, 1996, 1998, 1999, 2000, 2001, 2002, 2004\n\
The Regents of the University of California.  All rights reserved.\n";
static const char rcsid[] =
    "@(#) $Id: hf.l 1420 2005-09-29 22:25:14Z vern $ (LBL)";
#endif


#define HSIZE 8192		/* must be a power of two */

struct htable {
	char addr[NS_IN6ADDRSZ];
	int af;			/* address family */
	int alen;
	int state;
	char *name;		/* overloaded variable */
	struct htable *next;
} htable[HSIZE];

#define STATE_FREE	0	/* not in use */
#define STATE_RAW	1	/* couldn't translate */
#define STATE_SENTPTR	2
#define STATE_HAVEPTR	3
#define STATE_SENTA	4
#define STATE_HAVEA	5

int strip = 1;			/* strip local domain when possible */
int lcase = 1;			/* force lowercase */
int shortdomain;		/* strip entire domain */
int printboth;			/* print both addr & name */
#ifdef HAVE_ASYNC_DNS
int asyncdns;			/* 2 pass async dns hack */
int numasync;			/* number of outstanding async requests */
int asyncfd;
#endif
int networknumber;		/* convert to network numbers */
int check;			/* check PTR's against A records */
#ifdef DEBUG
int debug = 0;
#endif

int tmo;			/* seconds to wait for a answer from the dns */
int doingdns;			/* true if we're waiting for the nameserver */
jmp_buf alrmenv;		/* longjmp() buffer */

char *prog;

char domain[64];		/* current domain name (including '.') */
int domainlen;			/* length of domain name */

char azero[NS_IN6ADDRSZ];

#ifdef HAVE_ASYNC_DNS
struct nb_dns_info *nd;
#endif

int targc;
char **targv;

extern char *optarg;
extern int optind, opterr;

/* ANSI C defines this */
#ifndef __STDC__
extern char *malloc();
#endif

/* Forwards */
char *a2h(const char *, int, int);
char *addr2host(const char *, int, int);
#ifdef HAVE_ASYNC_DNS
void asyncreap(int);
#endif
struct htable *cacheaddr(const char *, int, int, int, const char *);
#ifdef DEBUG
void dump(void);
#endif
int getdomain(void);
struct htable *hash(const char *, int, int);
#ifdef HAVE_ASYNC_DNS
int ispipe(FILE *);
#endif
struct htable *lookupaddr(const char *, int, int);
int main(int, char **);
void massagename(char *);
RETSIGTYPE timeout(int);
void usage(void);

int
main(argc, argv)
	int argc;
	char **argv;
{
	register char *cp;
	register int op;
#ifdef HAVE_ASYNC_DNS
	char errstr[NB_DNS_ERRSIZE];
#endif

	if ((cp = strrchr(argv[0], '/')) != NULL)
		prog = cp + 1;
	else
		prog = argv[0];

	opterr = 0;
	while ((op = getopt(argc, argv, "1abcdilnNt:")) != EOF)
		switch (op) {

		case '1':
			++linemode;
			break;

		case 'a':
#ifdef HAVE_ASYNC_DNS
			++asyncdns;
#else
			fprintf(stderr,
			    "%s: warning: -a not supported; ignored\n", prog);
#endif
			break;

		case 'b':
			++printboth;
			break;

		case 'c':
			++check;
			break;

#ifdef DEBUG
		case 'd':
			++debug;
			break;
#endif

		case 'i':
			lcase = 0;
			break;

		case 'l':
			strip = 0;
			break;

		case 'n':
#ifdef notdef
			++networknumber;
#else
			fprintf(stderr, "%s: -n not currently impemented\n",
			    prog);
			exit(1);
#endif
			break;

		case 'N':
			++shortdomain;
			break;

		case 't':
			tmo = atoi(optarg);
			if (tmo <= 0)
				usage();
			break;

		default:
			usage();
		}

#ifdef HAVE_ASYNC_DNS
	if (asyncdns) {
		nd = nb_dns_init(errstr);
		if (nd == NULL) {
			fprintf(stderr, "%s: nb_dns_init: %s\n", prog, errstr);
			exit(1);
		}
		asyncfd = nb_dns_fd(nd);
		/* If no explicit timeout, use resolver retransmit */
		if (tmo == 0)
			tmo = _res.retrans;
	}
#endif

	/* Figure out our domain, if necessary */
	if (!strip || shortdomain || !getdomain())
		domain[0] = '\0';

	/* Up number of retries, we really want answers */
	_res.retry = 20;

	/* Don't search, we'll use only FQDNs */
	_res.options &= ~RES_DNSRCH;

	/* Setup alarm catcher if -t */
#ifdef HAVE_ASYNC_DNS
	if (!asyncdns)
#endif
		if (tmo > 0)
			(void)setsignal(SIGALRM, timeout);

	/* Let yywrap() figure out if there are any arguments to open */
	targc = argc - optind;
	targv = &argv[optind];
	yyin = NULL;
	(void)yywrap();

	/* Process file opened by yywrap() or stdin if no arguments */
	if (yyin) {
#ifdef HAVE_ASYNC_DNS
		/* XXX depends on the type of stdin */
		/* XXX can we do a test rewind? */
#ifdef notdef
		if (asyncdns && yyin == stdin)
			fprintf(stderr,
			    "%s: warning: can't use -a on stdin\n", prog);
#endif
#endif
		yylex();
	}

#ifdef DEBUG
	if (debug) {
		fflush(stdout);
		dump();
	}
#endif
	exit(0);
}

int
yywrap()
{
	register char *file;
	static int didany = 0;

	/* Close file, if necessary */
	if (yyin) {
#ifdef HAVE_ASYNC_DNS
		if (asyncdns) {
			if (lookup_pass) {
				if (fseek(yyin, 0L, SEEK_SET) < 0) {
					fprintf(stderr,
					    "%s: fseek/rewind: %s\n",
					    prog, strerror(errno));
					exit(1);
				}
				yyrestart(yyin);
				lookup_pass = 0;
				asyncreap(1);
				return (0);
			}
			numasync = 0;
		}
#endif
		if (yyin != stdin)
			(void)fclose(yyin);
		yyin = NULL;
	}

	/* Spin through arguments until we run out or successfully open one */
	while (targc > 0) {
		file = targv[0];
		--targc;
		++targv;
		++didany;
		if ((yyin = fopen(file, "r")) != NULL) {
#ifdef HAVE_ASYNC_DNS
			if (asyncdns)
				lookup_pass = 1;
#endif
			return (0);
		}
		perror(file);
	}
	if (!didany) {
		yyin = stdin;
#ifdef HAVE_ASYNC_DNS
		if (asyncdns) {
			if (ispipe(yyin)) {
				fprintf(stderr,
				    "%s: warning: can't use -a on a pipe\n",
				    prog);
				asyncdns = 0;
			} else
				lookup_pass = 1;
		}
#endif
	}
	return (1);
}

int
getdomain()
{
	register char *cp;
	register struct hostent *hp;
	char host[128];

	if (gethostname(host, sizeof(host) - 1) < 0)
		return (0);
	if ((cp = strchr(host, '.')) == NULL) {
		/* Not already canonical */
		if (tmo > 0)
			alarm(tmo);
		doingdns = 1;
		if (setjmp(alrmenv))
			return (0);
		hp = gethostbyname(host);
		doingdns = 0;
		if (hp == NULL)
			return (0);
		if ((cp = strchr(hp->h_name, '.')) == NULL)
			return (0);
	}
	(void)strncpy(domain, cp, sizeof(domain));
	domain[sizeof(domain) - 1] = '\0';
	if (lcase)
		for (cp = domain; *cp; ++cp)
			if (isupper((int)*cp))
				*cp = tolower(*cp);
	domainlen = strlen(domain);
	return (1);
}

RETSIGTYPE
timeout(int signo)
{

	if (doingdns) {
		doingdns = 0;
		longjmp(alrmenv, 1);
	}
	return RETSIGVAL;
}

/* Convert address to hostname via the dns */
char *
a2h(register const char *ap, register int alen, register int af)
{
	register char **pp;
	register size_t len;
	static struct hostent *hp;
	static char *host = NULL;
	static size_t hostlen = 0;

	/* Look up the PTR */
	if (tmo > 0)
		alarm(tmo);
	doingdns = 1;
	if (setjmp(alrmenv))
		return (NULL);
	hp = gethostbyaddr(ap, alen, af);
	doingdns = 0;
	if (hp == NULL)
		return (NULL);

	len = strlen(hp->h_name) + 1;
	if (hostlen < len) {
		if (len < 132)
			len = 132;
		if (host == NULL)
			host = malloc(len);
		else
			host = realloc(host, len);
		if (host == NULL) {
			hostlen = 0;
			return (NULL);
		}
		hostlen = len;
	}
	(void)strcpy(host, hp->h_name);

	/* Done if we aren't checking */
	if (!check)
		return (host);

#ifndef HAVE_GETHOSTBYNAME2
	if (af != AF_INET)
		return (NULL);
#endif

	/* Check PTR against the A record */
	if (tmo > 0)
		alarm(tmo);
	doingdns = 1;
	if (setjmp(alrmenv))
		return (NULL);
#ifdef HAVE_GETHOSTBYNAME2
	hp = gethostbyname2(host, af);
#else
	hp = gethostbyname(host);
#endif
	doingdns = 0;
	if (hp == NULL)
		return (NULL);
	if (af != hp->h_addrtype)
		return (NULL);

	/* Spin through ip addresses looking for a match */
	for (pp = hp->h_addr_list; *pp != NULL; ++pp)
		if (memcmp(ap, *pp, alen) == 0)
			return (host);

	return (NULL);
}

/* Convert address to hostname via the cache and/or dns */
char *
addr2host(register const char *ap, register int alen, register int af)
{
	register int state;
	register char *host;
	register struct htable *p;

	/* First look in hash table */
	p = lookupaddr(ap, alen, af);
	if (p != NULL)
		return (p->name);

	/* Lookup this host */
	host = a2h(ap, alen, af);
	state = STATE_RAW;
	if (host != NULL) {
		if (check)
			state = STATE_HAVEA;
		else
			state = STATE_HAVEPTR;
		massagename(host);
	}

	p = cacheaddr(ap, state, alen, af, host);
	if (p != NULL)
		return (p->name);

	return (host);
}

/* Look hash table entry for address */
struct htable *
lookupaddr(register const char *ap, register int alen, register int af)
{
	register struct htable *p;

	for (p = hash(ap, alen, af); p != NULL; p = p->next)
		if (p->af == af && memcmp(p->addr, ap, alen) == 0)
			return (p);
	return (NULL);
}

void
massagename(register char *name)
{
	register char *cp;

	if (shortdomain) {
		/* Throw away entire domain */
		cp = strchr(name, '.');
		if (cp)
			*cp = '\0';
	} else if (strip && *domain != '\0') {
		/* Strip the local domain */
		cp = name + strlen(name) - domainlen;
		if (cp > name && strcasecmp(cp, domain) == 0)
			*cp = '\0';
	}
	if (lcase)
		for (cp = name; *cp; ++cp)
			if (isupper((int)*cp))
				*cp = tolower(*cp);
}

struct htable *
cacheaddr(register const char *ap, register int state, register int alen,
    register int af, register const char *host)
{
	register struct htable *p, *p2;

	/* Don't cache zero */
	if (memcmp(ap, azero, alen) == 0)
		return (NULL);

	/* Look for existing slot in hash table */
	for (p = hash(ap, alen, af); p != NULL; p = p->next)
		if (p->state != STATE_FREE &&
		    p->af == af &&
		    memcmp(p->addr, ap, alen) == 0)
			break;

	/* Allocate a new slot */
	if (p == NULL) {
		p = hash(ap, alen, af);
		if (p->state != STATE_FREE) {
			/* Handle the collision */
			p2 = (struct htable *)malloc(sizeof(struct htable));
			/* Lose, lose */
			if (p2 == NULL)
				return (NULL);
			memset((char *)p2, 0, sizeof(struct htable));
			p2->next = p->next;
			p->next = p2;
			p = p2;
		}
	}

	/* Install new host */
	memmove(p->addr, ap, alen);
	p->alen = alen;
	p->af = af;
	if (host != NULL)
		p->name = strdup(host);
	if (state != 0)
		p->state = state;
	if (p->state == STATE_FREE)
		abort();

	/* Return answer entry */
	return (p);
}

#ifdef DEBUG
void
dump()
{
	register char *cp;
	register int i, j, n, d;
	register struct htable *p, *p2;
	char buf[132];

	d = n = 0;
	for (p = htable, i = 0; i < HSIZE; ++p, ++i)
		if (p->name) {
			++n;
			j = 0;
			for (p2 = p; p2; p2 = p2->next) {
				if ((cp = p2->name) == NULL)
					cp = "<nil>";
				else if (cp == (char *)1)
					cp = "<raw>";
				(void)fprintf(stderr, "%4d:%d ", i, j);
				if (inet_ntop(p2->af, p2->addr,
				    buf, sizeof(buf)) == NULL)
					(void)fprintf(stderr, "?");
				else
					(void)fprintf(stderr, "%s", buf);
				switch (p2->state) {

				case STATE_HAVEA:
					(void)fprintf(stderr, " HAVEA");
					break;

				case STATE_HAVEPTR:
					(void)fprintf(stderr, " HAVEPTR");
					break;

				case STATE_SENTPTR:
					(void)fprintf(stderr, " SENTPTR");
					break;

				case STATE_RAW:
					(void)fprintf(stderr, " RAW");
					break;

				default:
					(void)fprintf(stderr, " #%d",
					    p2->state);
					break;
				}
				(void)fprintf(stderr, " \"%s\"\n", cp);
				++d;
				++j;
			}
		}
	d -= n;
	(void)fprintf(stderr, "%d entries (%d dynamically linked)\n", n, d);
}
#endif

#ifdef HAVE_ASYNC_DNS
void
asyncreap(register int ateof)
{
	register char *host;
	register int n;
	register char **pp;
	register struct htable *p;
	register struct nb_dns_result *nr;
	register struct hostent *hp;
	fd_set fds;
	struct timeval to;
	char errstr[NB_DNS_ERRSIZE];
	struct nb_dns_result xxxnr;

	nr = &xxxnr;
	memset(nr, 0, sizeof(*nr));
	while (numasync > 0) {
		FD_ZERO(&fds);
		FD_SET(asyncfd, &fds);
		/* If we're not at EOF, just poll */
		if (!ateof) {
			to.tv_sec = 0;
			to.tv_usec = 0;
		} else {
			to.tv_sec = tmo;
			to.tv_usec = 0;
		}
		n = select(asyncfd + 1, &fds, NULL, NULL, &to);
		if (n < 0) {
			fprintf(stderr, "%s: select: %s\n",
			    prog, strerror(errno));
			exit(1);
		}

		/* Done if timed out */
		if (n == 0)
			break;

		n = nb_dns_activity(nd, nr, errstr);
		if (n < 0) {
			fprintf(stderr, "%s: nb_dns_activity: %s\n",
			    prog, errstr);
			exit(1);
		}

		/* Bail if reply doesn't match any current queries */
		if (n == 0)
			continue;

		/* Decrement outstanding request counter */
		--numasync;

		/* Bail if not a good answer */
		if (nr->host_errno != NETDB_SUCCESS)
			continue;

		/* Bail if no hostname (probably shouldn't happen) */
		hp = nr->hostent;
		host = hp->h_name;
		if (host == NULL)
			continue;

		/* Recover hash table pointer */
		p = (struct htable *)nr->cookie;

		switch (p->state) {

		case STATE_SENTPTR:
			/* Are we done? */
			if (!check) {
				p->state = STATE_HAVEPTR;
				break;
			}

			/* Now look up the A record */
			if (nb_dns_host_request2(nd, host, p->af,
			    (void *)p, errstr) < 0) {
				fprintf(stderr, "%s: nb_dns_host_request: %s\n",
				    prog, errstr);
				p->state = STATE_RAW;
				free(p->name);
				p->name = NULL;
				break;
			}

			/* Cache the fact that we're looking */
			++numasync;
			p->state = STATE_SENTA;
			break;

		case STATE_SENTA:
			/* Check A against our address */
			if (p->af != hp->h_addrtype) {
				p->state = STATE_RAW;
				free(p->name);
				p->name = NULL;
				break;
			}

			/* Spin through ip addresses looking for a match */
			for (pp = hp->h_addr_list; *pp != NULL; ++pp)
				if (memcmp(p->addr, *pp, p->alen) == 0)
					break;

			if (pp == NULL) {
				p->state = STATE_RAW;
				free(p->name);
				p->name = NULL;
				break;
			}
			p->state = STATE_HAVEA;
			break;

		default:
			abort();
		}
		massagename(host);
		if (p->name != NULL)
			abort();
		if (host != NULL)
			p->name = strdup(host);
	}
}
#endif

void
convert(register const char *str, register int isv6)
{
	register char *host;
	register int alen;
	register int af;
#ifdef HAVE_ASYNC_DNS
	register struct htable *p;
	char errstr[NB_DNS_ERRSIZE];
	static int num = 0;
#endif
	char addr[NS_IN6ADDRSZ];

	if (isv6) {
#ifdef AF_INET6
		af = AF_INET6;
		alen = NS_IN6ADDRSZ;
#else
#ifdef HAVE_ASYNC_DNS
		if (!asyncdns || !lookup_pass)
#endif
			fputs(str, stdout);
		return;
#endif
	} else {
		af = AF_INET;
		alen = NS_INADDRSZ;
	}

#ifdef HAVE_ASYNC_DNS
	if (asyncdns && lookup_pass) {
		if (inet_pton(af, str, addr) != 1)
			return;

		/* Done if already in hash table */
		if (lookupaddr(addr, alen, af) != NULL)
			return;

		p = cacheaddr(addr, STATE_SENTPTR, alen, af, NULL);
		if (p == NULL)
			return;

		if (nb_dns_addr_request2(nd, addr, af,
		    (void *)p, errstr) >= 0) {
			/* Cache the fact that we're looking */
			++numasync;
			++num;
		} else
			fprintf(stderr, "%s: nb_dns_host_request: %s\n",
			    prog, errstr);
		/* reap replies after we send a number of queries */
		if (num > 10) {
			asyncreap(0);
			num = 0;
		}
		return;
	}
#endif

	if (linemode && triedone) {
		fputs(str, stdout);
		return;
	}
	++triedone;

	if (inet_pton(af, str, addr) == 1) {
		host = addr2host(addr, alen, af);
		if (host != NULL) {
			fputs(host, stdout);
			if (printboth) {
				putchar('(');
				fputs(str, stdout);
				putchar(')');
			}
			return;
		}
	}
	fputs(str, stdout);
}

struct htable *
hash(register const char *ap, register int alen, register int af)
{
	u_int32_t h;

	switch (alen) {

	case NS_INADDRSZ:
		memmove(&h, ap, sizeof(h));
		break;

	case NS_IN6ADDRSZ:
		memmove(&h, ap + NS_IN6ADDRSZ - sizeof(h), sizeof(h));
		break;

	default:
		abort();
	}
	return (&htable[h & (HSIZE - 1)]);
}

#ifdef HAVE_ASYNC_DNS
int
ispipe(FILE *f)
{
	struct stat sbuf;

	if (fstat(fileno(f), &sbuf) < 0) {
		fprintf(stderr, "%s: fstat: %s\n", prog, strerror(errno));
		exit(1);
	}
	if ((sbuf.st_mode & S_IFMT) != S_IFREG)
		return (1);
	return (0);
}
#endif

void
usage()
{
	extern char version[];

	(void)fprintf(stderr, "Version %s\n", version);
	(void)fprintf(stderr, "usage: %s [-1abcdilN] [-t secs] [file ...]\n",
	    prog);
	exit(1);
}

